# Generated by Django 4.1.7 on 2023-03-18 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RefuelApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gallonsPumped', models.DecimalField(decimal_places=3, max_digits=6)),
                ('pricePerGallon', models.DecimalField(decimal_places=3, max_digits=6)),
                ('milesDriven', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gasStationLong', models.DecimalField(decimal_places=16, max_digits=22)),
                ('gasStationLat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RefuelApi.vehicle')),
            ],
        ),
    ]
